### ISSUE TITLE
Networking.ReferenceApplication - problem with build

### ISSUE THREAD

**Issue by AdamBorowiecki** [mpostol/OPC-UA-OOI#224]
There is build error:
The type or namespace 'CommonServiceLocator' could be not found.

**Comment by mpostol** [comment]
The Nuget package must be updated. Current copy in repo uses 2.0.1. Previous version had different namespace.

**Comment by AdamBorowiecki** [comment]
Yes, I handle it. I only want to suggest that we should be able to build project after git pull(without any additional action).

**Comment by mpostol** [comment]
The repo is updated and refers only to the new version, so after cloning the new version of nuget packages are downloaded. I have tested it.

I am not sure what happens after pulling for existing copy because the current version referenced is in the packages folder that is ignored for pushing. 

Anyway, now the repo refers only to the new version, and the code had been fixed accordingly. 

I assume that we can close this issue without any additional action.
